### ISSUE TITLE
[BUG] 開発中最新公式ルールのコアフロー[10-3]～[10-9]

### ISSUE THREAD

**Issue by gomentai** [BlackPoker/BlackPoker#115]
**Describe the bug** (バグの説明)
例えば、リストに「プレイヤーA：即時アクション1と2、プレイヤーB：即時アクション3と4」がある状態で[10-3]に遷移したケースを考える。Aがターンプレイヤー。
即時アクション1と2が解決され「プレイヤーA：なし、プレイヤーB：即時アクション3と4」の状態でプレイヤーBの[10-4]に遷移。
[10-5]で即時アクション3が解決されたときにプレイヤーAがコントローラーである即時アクション5とBの即時アクション6が誘発すると、[10-7]でリストは「プレイヤーA：即時アクション5、プレイヤーB：即時アクション4と6」となる。
このとき、次に解決されるアクションはどれか。
- 4
- 5
- 4or6（Bの選択）

**Expected behavior** (どうなってるのが正しそう？)
上記の曖昧さのないフロー図にする。

**Screenshots** (スクリーンショット)
![image](https://user-images.githubusercontent.com/75535087/158000363-e8ba5f39-a518-4baf-a24f-e2b7be1a2f60.png)

**Comment by BlackPoker** [comment]
@gomentai 
コメントありがとうございます！

動作としては次のようになります。
* 4or6（Bの選択）

## 理由

```
[10-7]でリストは「プレイヤーA：即時アクション5、プレイヤーB：即時アクション4と6」
```
このコメントもの前に「プレイヤーBの[10-4]に遷移」とあるので、この操作はプレイヤーBが行っています。
この状態で、[10-8]を判断すると「プレイヤーB：即時アクション4と6」であるため、プレイヤーBの操作のまま[10-4]に遷移します。
ここでプレイヤーBは[10-4]の操作を行うため、

* 4or6（Bの選択）

となります。

おそらく、操作をしているプレイヤーがどこで切り替わるかが分かりづらいため曖昧に見えたのかもしれません。

この処理は二重ループとなっています。

外側のループ：プレイヤー単位に繰り返し
内側のループ：プレイヤーがコントローラーとなっているアクション単位のループ

[10-6]で誘発したアクションに関しては、操作中のプレイヤーがコントローラとなっているアクションのほうが先に解決されることに違和感があり、曖昧に見えたのかもしれません。

## 背景

このルールの場合、誘発し続ければプレイヤーBが常に操作し続ける可能性があります。
そこは、アクションの定義側で整理するとしこのルールにしました。

ルールを決めるで上で優先したことは、変数を減らすことでした。
アクションが解決される順番を発生した順番を記録しルール側で決める場合、変数の構造が複雑になり、管理する情報が増えると考えました。
そのため、現在の状態に整理しました。



更にコメントいただけるとありがたいです。

**Comment by BlackPoker** [comment]
追加のコメントがないのでクローズとします。
