### ISSUE TITLE
[KAIZEN] プリセットに関するルール修正案

### ISSUE THREAD

**Issue by gomentai** [BlackPoker/BlackPoker#125]
**As-Is**(現状の問題)
プリセットに関する規定がない。
**To-Be**(どうしたらいいか)
プリセットのルールを追加する。
--
ルールの修正案です。
（修正案）
3.9. ゲームの始め方
次の手順でゲームを始めます。
1. デッキをよく切る。
2. **プリセット2の場合、デッキの一番上のカードを裏向きで防壁として場に出し、デッキの上からもう1枚のカードを表向きで兵士として場に出す。**
3. **プリセット4の場合、デッキの上から2枚のカードを裏向きで防壁（2体）として場に出し、デッキの上からもう2枚のカードを表向きで兵士（2体）として場に出す。**
4. デッキより7枚引き手札にする。
5. 両者デッキの一番上を表にする。
6. 大きい数字のプレイヤーが先攻。数字については、 cardrank 参照。
7. 数字が同じ場合、さらにデッキの一番上を表にし同様のルールで比べる。
8. 表にしたカードを墓地へ移す。
9. 先攻プレイヤーはデッキより1枚引き手札に加える。
10. 先攻プレイヤーがターンとチャンスをもちゲームを開始する。

（現行）
3.9. ゲームの始め方
次の手順でゲームを始めます。
1.	デッキをよく切る。
2.	デッキより7枚引き手札にする。
3.	両者デッキの一番上を表にする。
4.	大きい数字のプレイヤーが先攻。数字については、 cardrank 参照。
5.	数字が同じ場合、さらにデッキの一番上を表にし同様のルールで比べる。
6.	表にしたカードを墓地へ移す。
7.	先攻プレイヤーはデッキより1枚引き手札に加える。
8.	先攻プレイヤーがターンとチャンスをもちゲームを開始する。

**Comment by BlackPoker** [comment]
７版で追加されたオプションにて、記載済み。
クローズします。
