### ISSUE TITLE
[BUG] 自分のターンの始め方に誤記

### ISSUE THREAD

**Issue by morinokumasn** [BlackPoker/BlackPoker#19]
**Describe the bug** (バグの説明)
(バグの内容を簡単に説明してください。)
「自分のターンの始め方」に @<br>{}の文字列が表示され、連番で表記されていません。

**To Reproduce** (再現方法について)
（バグを再現する手順を記載してください。）
以下のページを開いてください。
https://blackpoker.github.io/BlackPoker/master/common/02-turn.html#id3

**Expected behavior** (どうなってるのが正しそう？)
(何が起きていると予想されますか？)
連番が正しく振られ文章が表示されることが正しいと思われます。

**Screenshots** (スクリーンショット)
(バグの説明に役立つスクリーンショットがあれば追加してください。)
![image](https://user-images.githubusercontent.com/36735932/119226895-60bc7380-bb46-11eb-9cc3-d9ae283e0881.png)

**Desktop (please complete the following information):** (動作環境について-PC)
 - OS: MacOS
 - Browser chrome
 - Version バージョン: 90.0.4430.212（Official Build） （x86_64）

**Additional context** (備考)
(バグに関する補足事項を記載してください。)

**Comment by BlackPoker** [comment]
修正完了しました。
