### ISSUE TITLE
フォーマット定義がライトのみになってる

### ISSUE THREAD

**Issue by BlackPoker** [BlackPoker/BlackPoker#2]
フォーマットにてライトしか定義されていません。
![image](https://user-images.githubusercontent.com/36736124/101234640-6c38f100-3704-11eb-8ff4-46ed853b2e68.png)

**Comment by gomentai** [comment]
エクストラ（フォーマット）の定義の案です。
-
**◆エクストラ（フォーマット）**
〇アクションリスト
- 《マスターのアクションリストパスを記載する》

〇エクストラリスト
- 《エクストラリストパスを記載する》

〇事前準備
- デッキに使用できるカードセットの中から最大2枚のカードを選び切札とし、残りのカードのすべてまたは一部をデッキとする。

〇その他事項
- 切札はデッキと角度を変えて交わるようにデッキの下に置く。

**Comment by gomentai** [comment]
質問です。上記でエクストラ（フォーマット）の定義の案を示しましたが、「ルールの構成」をよく見ていませんでした。
エクストラは「拡張フォーマット」として定義するもののようなので、「通常フォーマット」と「拡張フォーマット」の違いについて教えてください。定義項目が違うということでしょうか？
-
![image](https://user-images.githubusercontent.com/75535087/102706443-4e0eeb80-42d5-11eb-8a2c-b1cb494565d2.png)

**Comment by BlackPoker** [comment]
> ## 質問です。上記でエクストラ（フォーマット）の定義の案を示しましたが、「ルールの構成」をよく見ていませんでした。
> エクストラは「拡張フォーマット」として定義するもののようなので、「通常フォーマット」と「拡張フォーマット」の違いについて教えてください。定義項目が違うということでしょうか？
> ![image](https://user-images.githubusercontent.com/75535087/102706443-4e0eeb80-42d5-11eb-8a2c-b1cb494565d2.png)

通常フォーマットと拡張フォーマットの違いについて回答します。

通常フォーマット：基本となるアクションの定義
拡張フォーマット：通常フォーマットをもとに拡張したフォーマット

よって、通常フォーマットと拡張フォーマットは組合せることができます。
例えばライト＋切札なども可能になります。

**Comment by BlackPoker** [comment]
* フォーマットを追加
* 拡張フォーマットの表記を削除
