### ISSUE TITLE
用語の定義

### ISSUE THREAD

**Issue by gomentai** [BlackPoker/BlackPoker#34]
@BlackPoker 
効果の発揮、効果の解決、能力の発揮などの意味の違いを考えて用語の定義（案）を作成してみました。
能力：ある条件が満たされた場合に効果を発揮する機能。
効果：アクションや能力によりもたらされる結果。
発揮：アクションや能力が効果をもたらすこと。
解決：アクションの効果を発揮させること。
（関連個所）
![image](https://user-images.githubusercontent.com/75535087/122934879-df593a80-d3aa-11eb-9c7c-7bc22223ecb6.png)
![image](https://user-images.githubusercontent.com/75535087/122935051-fdbf3600-d3aa-11eb-9e89-b1bbfe8c5f33.png)

**Comment by BlackPoker** [comment]
ご指摘ありがとうございます！

【能力】
能力の発揮=誘発型能力を指してると思います。
能力の発揮という記載はなかったと思います。
定義する言葉が増えると混乱するとおもうので、能力についてはこのままとしたいです。

【効果】
効果を発揮、効果を解決の表記が重複になってると思います。

効果を発揮=効果を解決する前
効果を解決=効果を発揮した後

発揮か解決で表記を統一しようかと思います。。

効果を解決:効果欄の内容を行う

**Comment by gomentai** [comment]
「効果」や「解決」という用語は広く使われているので、一旦表記を統一する修正を行ってからレビューした方がいいと思います。
「能力を発揮する」については、次のように数か所に記述があります。
![image](https://user-images.githubusercontent.com/75535087/123137244-b9a56180-d48e-11eb-9687-f4394399bab4.png)
![image](https://user-images.githubusercontent.com/75535087/123137453-f2453b00-d48e-11eb-9106-659dcc86c7f3.png)
![image](https://user-images.githubusercontent.com/75535087/123137593-156fea80-d48f-11eb-8013-e0737c002955.png)
![image](https://user-images.githubusercontent.com/75535087/123137654-2caed800-d48f-11eb-9a9b-8a3503da7082.png)
![image](https://user-images.githubusercontent.com/75535087/123137856-67b10b80-d48f-11eb-8b1e-0d312b9ca039.png)
![image](https://user-images.githubusercontent.com/75535087/123137910-74cdfa80-d48f-11eb-95e1-3c175455dc93.png)

**Comment by BlackPoker** [comment]
ご意見ありがとうございます。
全体を見直して修整します。

**Comment by BlackPoker** [comment]
能力を明確に定義したほうが良い。

![image](https://user-images.githubusercontent.com/36736124/123496365-bebb0a00-d662-11eb-8aa6-ee5286cacea0.png)

（誤）
能力とはアクションの効果とは異なる概念で、アクションを起こすことができたり、 アクションを誘発したりすることができます。

（正）
能力とはアクションの効果とは異なる概念で、アクションを起こすことができたり、 アクションを誘発したりすることがでる力です。

**Comment by BlackPoker** [comment]
能力は発揮、有効
→発揮は誘発？
→能力は有効に統一？

効果は発揮され解決される
→昔から発揮といってる
→発揮と解決は一緒といってもよい
→発揮され、解決されるという使い方でも良さそう。
→解決は完了した感じ、発揮は完了してない感じ
→自動詞他動詞、発揮するは自動詞、解決されるは他動詞
→アクションを解決する＝
→効果が解決される様子を効果を発揮する？
→統一すると自動詞他動詞問題、過去未来問題が発生するかも？


・能力を有効、無効が整理されていれば良さそう。
→能力の有効無効はコアルールで定義して、あとは有効無効に書き換える
・効果の解決、発揮問題影響範囲が大きそう。。→別issueにする

**Comment by BlackPoker** [comment]
このissueでは、能力の文言統一のみ行い、効果の解決、発揮については以下のissueで対応します。
#56

能力は有効、無効で整理します。

**Comment by BlackPoker** [comment]
@gomentai 
修正が完了しました。
コメントがある場合は、別途issueを作成して下さい。
