### ISSUE TITLE
「カウンター」アクションの改良案

### ISSUE THREAD

**Issue by gomentai** [BlackPoker/BlackPoker#35]
カウンターアクションの修正案です。
「5ダウンは5以上のカウンターで打ち消すことができる」のような説明をしやすくするのが目的です。
キーカードの数字の大小判定はアクション解決時に行います。
**●修正案**
【カウンター】速攻魔法
@クイック $D ★♣A～10
（対象）
キーカードが1枚または2枚のアクションを対象とする。
（通常効果）
次のいずれかの場合、対象のアクションは効果を発揮しない。その場合、対象アクションをステージから取り除き、対象アクションのキーカードを墓地に移す。
・対象アクションのキーカードが1枚かつこのアクションのキーカードの数字が対象アクションのキーカードの数字以上
・対象アクションのキーカードが2枚
**●現行**
【カウンター】速攻魔法
@クイック $D ★♣A～10
（対象）
以下のいずれかの条件に該当するアクションを対象とする。Xはこのアクションのキーカードの数字とする。
・キーカードが1枚かつそのキーカードの数字がX以下
・キーカードが2枚
（通常効果）
対象のアクションは効果を発揮しない。対象アクションをステージから取り除き、対象アクションのキーカードを墓地に移す。
![image](https://user-images.githubusercontent.com/75535087/122998129-a12e3c00-d3e7-11eb-89d6-0b6afebfe65f.png)

**Comment by BlackPoker** [comment]
ご意見ありがとうございます！

修整案だと現行と対象範囲が変更となってしまいます。
対象範囲は維持したいです。

アクション全体として長文になるものが多くあります。
短縮表示と詳細表示を実装すれば解決されますか？

**Comment by gomentai** [comment]
「対象範囲を維持する」と「アクション宣言をシンプルにする」は相反するので、前者を優先するなら修正案は却下されます。後者を優先するなら修正案は有力だと思います。
特に初心者に教える場合、「自分にチャンスがあるときに起こすことが可能なアクションは何か」ということがわかりやすくなります。まずアクションを起こすことができるかできないかを確認し、次に（起こすことができる場合は）それが自分に有利な結果をもたらすか否かを考える、という2段階で検討することがやりやすくなります。

**Comment by BlackPoker** [comment]
ご意見ありがとうございます。
以下の理由で今回、カウンターアクションの内容を提案通り修整します。
* アップ、ダウン、ツイストとカウンターのみ対象範囲に統一感がない
* わかりやすさの最善
* 対象範囲が変更されてもゲームとして影響がない

盛り込み時期はissueに設定させるマイルストーンを確認してください。

**Comment by BlackPoker** [comment]
関連 #6

**Comment by BlackPoker** [comment]
@gomentai 
修正しましたので、クローズします。
ご指摘ありがとうございました。
更に指摘がある場合、再度issueを起票して下さい。
