### ISSUE TITLE
「クローズ」アクションは6版でコストを変更するのでは？

### ISSUE THREAD

**Issue by gomentai** [BlackPoker/BlackPoker#36]
「クローズ」アクションは次の変更が予定されていたと思います。
1. コストを「B」から「D」に変更。
2. 「通常効果」から「即時効果」に変更。
![image](https://user-images.githubusercontent.com/75535087/122999283-06366180-d3e9-11eb-9db5-09b2a5d48752.png)

**Comment by BlackPoker** [comment]
ご指摘ありがとうございます！
対応します。

**Comment by BlackPoker** [comment]
@gomentai 
対応が完了しました。
ご指摘ありがとうございました。
