### ISSUE TITLE
対戦レギュレーションにハーフ系のレギュレーションがない

### ISSUE THREAD

**Issue by BlackPoker** [BlackPoker/BlackPoker#42]
ライトランダムハーフなどのハーフ系対戦レギュレーションがレギュレーション定義に含まれていません。

関連
#13

**Comment by gomentai** [comment]
![image](https://user-images.githubusercontent.com/75535087/123497240-4dca2100-d667-11eb-8839-bfdce9b7ccc6.png)

**Comment by BlackPoker** [comment]
@gomentai 
ライトランダムハーフを追加しました。
再度コメントがありましたら、別途issueを作成して下さい。
