### ISSUE TITLE
[KAIZEN] 効果の解決、発揮が重複表現に見える

### ISSUE THREAD

**Issue by BlackPoker** [BlackPoker/BlackPoker#56]
**As-Is**(現状の問題)
効果に対して解決、発揮と同じことを２つの単語を使って表現している。

**To-Be**(どうしたらいいか)
解決か発揮のどちらかに統一してほしい。

**Reason**(理由)
同じことを別々の方法で記載されると混乱する

**Note**(備考)

**Comment by gomentai** [comment]
用語の定義を提案します。
効果：アクションの働き（アクションの「効果」欄に記載された内容）
発揮：効果をゲームに適用すること
解決：アクションの効果を発揮させること
「効果を解決」と言う代わりに「アクションを解決」と言うようにすればスッキリすると思います。

**Comment by BlackPoker** [comment]
アクション解決に統一

・3.10.4.  アクションの効果解決←矛盾している
・コアフローを効果解決→アクション解決
・3.10.4をアクション解決（現：効果解決）をアクション解決に該当するように記載する
・効果を発揮は効果欄に記載されているにようを実行する
