### ISSUE TITLE
[BUG] PDF版の表示が乱れている

### ISSUE THREAD

**Issue by gomentai** [BlackPoker/BlackPoker#59]
**Describe the bug** (バグの説明)
(バグの内容を簡単に説明してください。)
PDF版に「?? ??」のような表示が多数あります。
![image](https://user-images.githubusercontent.com/75535087/123547694-bebf2500-d79c-11eb-862a-eee8872cae11.png)

**To Reproduce** (再現方法について)
（バグを再現する手順を記載してください。）

**Expected behavior** (どうなってるのが正しそう？)
(何が起きていると予想されますか？)
![image](https://user-images.githubusercontent.com/75535087/123547866-6b010b80-d79d-11eb-9068-a8231292fb48.png)

**Screenshots** (スクリーンショット)
(バグの説明に役立つスクリーンショットがあれば追加してください。)

**Desktop (please complete the following information):** (動作環境について-PC)

**Smartphone (please complete the following information):** (動作環境について-スマートフォン)

**Additional context** (備考)
(バグに関する補足事項を記載してください。)

**Comment by BlackPoker** [comment]
@gomentai 
ご指摘ありがとうございます。
以下のissueにて対応中ですので、こちらはクローズします。
#24
