### ISSUE TITLE
[BUG] アクションリスト・エクストラリストの日付が違う

### ISSUE THREAD

**Issue by gomentai** [BlackPoker/BlackPoker#60]
**Describe the bug** (バグの説明)
(バグの内容を簡単に説明してください。)
![image](https://user-images.githubusercontent.com/75535087/123548042-27f36800-d79e-11eb-9726-ec7a339beec7.png)
![image](https://user-images.githubusercontent.com/75535087/123548067-3fcaec00-d79e-11eb-937e-7d377a09e5e0.png)
![image](https://user-images.githubusercontent.com/75535087/123548114-6c7f0380-d79e-11eb-9dc0-76afb78b69af.png)

**To Reproduce** (再現方法について)
（バグを再現する手順を記載してください。）

**Expected behavior** (どうなってるのが正しそう？)
(何が起きていると予想されますか？)

**Screenshots** (スクリーンショット)
(バグの説明に役立つスクリーンショットがあれば追加してください。)

**Desktop (please complete the following information):** (動作環境について-PC)

**Smartphone (please complete the following information):** (動作環境について-スマートフォン)

**Additional context** (備考)
(バグに関する補足事項を記載してください。)

**Comment by BlackPoker** [comment]
@gomentai 
修正しました！
