### ISSUE TITLE
[BUG] PDF版の目次がない

### ISSUE THREAD

**Issue by gomentai** [BlackPoker/BlackPoker#61]
**Describe the bug** (バグの説明)
(バグの内容を簡単に説明してください。)
![image](https://user-images.githubusercontent.com/75535087/123548343-5b82c200-d79f-11eb-9cfc-6f7adc462f38.png)

**To Reproduce** (再現方法について)
（バグを再現する手順を記載してください。）

**Expected behavior** (どうなってるのが正しそう？)
(何が起きていると予想されますか？)

**Screenshots** (スクリーンショット)
(バグの説明に役立つスクリーンショットがあれば追加してください。)

**Desktop (please complete the following information):** (動作環境について-PC)

**Smartphone (please complete the following information):** (動作環境について-スマートフォン)

**Additional context** (備考)
(バグに関する補足事項を記載してください。)

**Comment by BlackPoker** [comment]
@gomentai 
ご指摘ありがとうございます。
重複しているため以下のissueで管理します。
#41 
こちらはクローズさせていただきます。
