### ISSUE TITLE
[BUG] 脱字

### ISSUE THREAD

**Issue by gomentai** [BlackPoker/BlackPoker#62]
**Describe the bug** (バグの説明)
(バグの内容を簡単に説明してください。)
「40」のデッキ条件。
「次のカードの中から40までカードを選びデッキとする」
↓
「次のカードの中から40枚までカードを選びデッキとする」
![image](https://user-images.githubusercontent.com/75535087/123548581-52462500-d7a0-11eb-8204-a98c7a9cb0ed.png)

**To Reproduce** (再現方法について)
（バグを再現する手順を記載してください。）

**Expected behavior** (どうなってるのが正しそう？)
(何が起きていると予想されますか？)

**Screenshots** (スクリーンショット)
(バグの説明に役立つスクリーンショットがあれば追加してください。)

**Desktop (please complete the following information):** (動作環境について-PC)

**Smartphone (please complete the following information):** (動作環境について-スマートフォン)

**Additional context** (備考)
(バグに関する補足事項を記載してください。)

**Comment by BlackPoker** [comment]
@gomentai 
ご指摘ありがとうございます。
修正しました。
