### ISSUE TITLE
[BUG] 修正漏れ（能力を発揮）

### ISSUE THREAD

**Issue by gomentai** [BlackPoker/BlackPoker#75]
**Describe the bug** (バグの説明)
(バグの内容を簡単に説明してください。)
![image](https://user-images.githubusercontent.com/75535087/124385883-ab6b0700-dd12-11eb-8034-5f21088444d4.png)

**To Reproduce** (再現方法について)
（バグを再現する手順を記載してください。）

**Expected behavior** (どうなってるのが正しそう？)
(何が起きていると予想されますか？)

**Screenshots** (スクリーンショット)
(バグの説明に役立つスクリーンショットがあれば追加してください。)

**Desktop (please complete the following information):** (動作環境について-PC)

**Smartphone (please complete the following information):** (動作環境について-スマートフォン)

**Additional context** (備考)
(バグに関する補足事項を記載してください。)

**Comment by BlackPoker** [comment]
@gomentai 
ご指摘ありがとうございます！
修正します！

**Comment by BlackPoker** [comment]
修正しましたが、6th未反映
