### ISSUE TITLE
[KAIZEN] 対戦（match）、試合の単位を定義する

### ISSUE THREAD

**Issue by BlackPoker** [BlackPoker/BlackPoker#97]
**As-Is**(現状の問題)
ハーフ系の対戦レギュレーションに定義されている試合という単位関係がある。
単位の関係は対戦＞試合となっている。
定義としてはレギュレーション内にとどまっている

**To-Be**(どうしたらいいか)
他のレギュレーションも対戦＞試合の定義にそうべき。

**Reason**(理由)
対戦レギュレーションごとに言葉の使い方が異なると混乱するから。

**Note**(備考)

**Comment by gomentai** [comment]
昨日、「試合」という言葉があちこちにあると言いましたが、「ゲーム」の勘違いでした。
例えば、次の箇所で「デッキをシャッフルして手札を引き先攻プレイヤーが1枚引いて開始するものをゲームと定義」しています。
![image](https://user-images.githubusercontent.com/75535087/132122246-0090ebad-1d85-4807-87e6-54c6c28ecf86.png)
したがって、「ライトランダムハーフ」の対戦には2～3のゲームが含まれます。この対戦のことを「試合」と呼んでも矛盾はしませんが、「ゲーム」と「試合」を別の意味で使用するのは紛らわしいと思いますので、大会などの対戦（1ゲームまたは複数ゲームで勝敗を決める単位）のことは「マッチ」と言う方がいいと思います。

**Comment by BlackPoker** [comment]
#143 にて対応済み。クローズします。
