### ISSUE TITLE
[BUG] cardrankのリンクが効かない

### ISSUE THREAD

**Issue by gomentai** [BlackPoker/BlackPoker#98]
**Describe the bug** (バグの説明)
「cardrank」のリンクが無効です。

**To Reproduce** (再現方法について)
6.1版の共通ルールの中に2か所ほどあります。

**Expected behavior** (どうなってるのが正しそう？)
カードの数字の定義表へのリンク？

**Screenshots** (スクリーンショット)
![image](https://user-images.githubusercontent.com/75535087/132122007-b552535c-afea-4b6c-8f1b-ece7347549c6.png)

**Desktop (please complete the following information):** (動作環境について-PC)
 - OS: Windows10
 - Browser: Chrome
 - Version: バージョン: 93.0.4577.63（Official Build） （64 ビット）

**Comment by BlackPoker** [comment]
ご指摘ありがとうございます。
最新版で確認したところ、リンクが表示されていたので、クローズします。
<img width="632" alt="image" src="https://github.com/BlackPoker/BlackPoker/assets/36736124/caba5e20-9402-46fd-93a4-f17ea35ab6fc">
